[template]
rustc_version = "1.88.0" # Ensure compatibility with your Rust version

[placeholders.project_name]
type = "string"
prompt = "What is the project name?"
regex = "^[a-zA-Z][a-zA-Z0-9_-]*$"
description = "The name of the project, used in Cargo.toml. Must start with a letter or underscore and contain only letters, numbers, hyphens, or underscores."

[placeholders.database]
type = "string"
prompt = "Which database do you want to use?"
choices = ["postgres", "mysql", "sqlite"]