[template]
cargo_generate_version = ">=0.18.0"

[template.process]
include = [
    "**/*.rs",
    "**/*.yaml",
    ".env",
    "debug.txt"
]
exclude = ["Cargo.toml"]
[placeholders.description]
type = "string"
prompt = "\n\nProvide a short description of your project. This will appear in Cargo.toml and documentation."
default = "A Rust web server application built with Actix"

[placeholders.author_name]
type = "string"
prompt = "\n\nEnter your name. This will be listed as the author in Cargo.toml."
default = "Your Name"

[placeholders.database]
prompt = "\n\nChoose your database:    \n- postgres: PostgreSQL, a powerful relational database (requires a server).    \n- mysql: MySQL, a popular relational database (requires a server).    \n- sqlite: SQLite, a lightweight, file-based database (no server needed)."
type = "string"
choices = ["\n", "postgres", "mysql", "sqlite"]
default = "sqlite"
description = "The database backend for your project."

[placeholders.db_name]
type = "string"
prompt = "\n\nEnter the name of your database (e.g., 'mydb'). For SQLite, this will be the file name (e.g., 'mydb.sqlite').\n"
default = "mydb"
regex = "^[a-zA-Z][a-zA-Z0-9_-]*$"
description = "The name of the database used in the DATABASE_URL."

[placeholders.include_logging]
type = "bool"
prompt = "\n\nDo you want to include logging? This adds the log and log4rs crates for detailed logging to debug and monitor your application."
default = true

[placeholders.include_cors]
type = "bool"
prompt = "\n\nDo you want to include CORS support? This enables Cross-Origin Resource Sharing, needed if your API is accessed by web browsers from different domains."
default = true

[placeholders.server_port]
type = "string"
prompt = "\n\nSpecify the port for your server (e.g., '8080'). You can change this later in the .env file."
default = "8080"
regex = "^[0-9]+$"
description = "The port your web server will listen on."

[placeholders.use_docker]
type = "bool"
prompt = "\n\nDo you want to include Docker configuration? This generates a Dockerfile and docker-compose.yml to run your app and database in containers."
default = false


# Conditional file generation - CORRECT SYNTAX

[conditional.'include_logging == false']
ignore = ["log4rs.yaml"]

[conditional.'include_cors == false']
ignore = ["src/middleware/cors_mgt.rs", "src/middleware/mod.rs", "src/middleware/"]

[conditional.'use_docker == false']
ignore = ["Dockerfile", "docker-compose-postgres.yaml", "docker-compose-mysql.yaml", "docker-compose-sqlite.yaml"]

[conditional.'database == "sqlite" && use_docker == true']
ignore = ["docker-compose-postgres.yaml", "docker-compose-mysql.yaml"]

[conditional.'database == "mysql" && use_docker == true']
ignore = ["docker-compose-postgres.yaml", "docker-compose-sqlite.yaml"]

[conditional.'database == "postgres" && use_docker == true']
ignore = ["docker-compose-sqlite.yaml", "docker-compose-mysql.yaml"]
