[package]
name = "{{project_name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-governor = "0.8.0"
actix-web = "4.9.0"
chrono = { version = "0.4.40", features = ["serde"] }
dotenv = "0.15.0"
log = "0.4.26"
log4rs = "1.3.0"
rust_decimal = "1.36.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
sqlx = { version = "0.8.3", features = ["{{database}}", "runtime-tokio", "rust_decimal", "chrono", "uuid"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
uuid = { version = "1.15.1", features = ["v4", "serde"] }