version: '3.8'

services:
  app:
    build: .
    ports:
      - "{{server_port}}:{{server_port}}"
    env_file:
      - .env
    depends_on:
      {% if database == "postgres" %}- db{% elif database == "mysql" %}- db{% endif %}

{% if use_docker and (database == "postgres" or database == "mysql") %}
  db:
    {% if database == "postgres" %}
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{db_name}}
    {% elif database == "mysql" %}
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: {{db_name}}
    {% endif %}
    ports:
      - "{% if database == "postgres" %}5432{% else %}3306{% endif %}:{% if database == "postgres" %}5432{% else %}3306{% endif %}"
{% endif %}