version: '3.8'

services:
  app:
    build: .
    ports:
      - "{{server_port}}:{{server_port}}"
    env_file:
      - .env
    # The 'if' block now wraps the entire 'depends_on' section.
    # The '-' in {%- and -%} removes extra whitespace.
    {% if database == "postgres" or database == "mysql" -%}
    depends_on:
      - db
    {%- endif %}

  # Only add the 'db' service if a server-based database is chosen.
  {% if database != "sqlite" -%}
  db:
    # Conditionally include the postgres configuration.
    {% if database == "postgres" -%}
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{db_name}}
    ports:
      - "5432:5432"
    {%- endif %}
    
    # Conditionally include the mysql configuration.
    {% if database == "mysql" -%}
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: {{db_name}}
    ports:
      - "3306:3306"
    {%- endif %}
  {%- endif %}