version: '3.8'

services:
  app:
    build: .
    ports:
      - "{{server_port}}:{{server_port}}"
    env_file:
      - .env
    {% if database == "postgres" or database == "mysql" %}depends_on:
      - db{% endif %}

{% if use_docker and (database == "postgres" or database == "mysql") %}
  db:
    {% if database == "postgres" %}
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{db_name}}
    ports:
      - "5432:5432"
    {% elif database == "mysql" %}
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: {{db_name}}
    ports:
      - "3306:3306"
    {% endif %}
{% endif %}