version: '3.8'
services:
  app:
    build: .
    ports:
      - "{{server_port}}:{{server_port}}"
    env_file: .env
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{db_name}}"
    ports:
      - "3306:3306"